package Frontera;

import javax.swing.JOptionPane;

public class Asignacion extends javax.swing.JPanel {

    private NuevaAsignacion nueva = new NuevaAsignacion();

    public Asignacion() {
        initComponents();
        inicioAsignacion();
    }

    public void inicioAsignacion() {
        principalAsignacion.setVisible(false);
        principalAsignacion.removeAll();
        principalAsignacion.add(inicioAsignacion);
        principalAsignacion.setVisible(true);
        back.setVisible(false);
    }

    public void validarInicioAsignacion() {
        if (nueva.validarCampos()) {
            int selCon = JOptionPane.showConfirmDialog(null, "¿Desea volver al inicio?", "Confirmación", JOptionPane.OK_CANCEL_OPTION);
            if (selCon == 0) {
                principalAsignacion.setVisible(false);
                principalAsignacion.removeAll();
                principalAsignacion.add(inicioAsignacion);
                principalAsignacion.setVisible(true);
                back.setVisible(false);
            }
        } else {
            int selCon = JOptionPane.showConfirmDialog(null, "¿Desea guardar los cambios?", "Confirmación", JOptionPane.OK_CANCEL_OPTION);
            if (selCon == 0) {
                System.out.println("Datos guardados");
                principalAsignacion.setVisible(false);
                principalAsignacion.removeAll();
                principalAsignacion.add(inicioAsignacion);
                principalAsignacion.setVisible(true);
                back.setVisible(false);
                nueva.vaciarCampos();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloAsignacion = new javax.swing.JPanel();
        asignacion = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        principalAsignacion = new javax.swing.JPanel();
        inicioAsignacion = new javax.swing.JPanel();
        asignacionNuevaIcon = new javax.swing.JLabel();
        asignacionNuevaLabel = new javax.swing.JLabel();
        asignacionVerIcon = new javax.swing.JLabel();
        asignacionVerLabel = new javax.swing.JLabel();
        asignacionEditarIcon = new javax.swing.JLabel();
        asignacionEditarLabel = new javax.swing.JLabel();

        tituloAsignacion.setBackground(new java.awt.Color(113, 166, 111));
        tituloAsignacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        asignacion.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        asignacion.setForeground(new java.awt.Color(19, 38, 35));
        asignacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignacion.setText("ASIGNACIÓN");
        tituloAsignacion.add(asignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, -1, 1120, 80));

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/arrow.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        tituloAsignacion.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        principalAsignacion.setBackground(new java.awt.Color(19, 38, 35));
        principalAsignacion.setLayout(new java.awt.BorderLayout());

        inicioAsignacion.setBackground(new java.awt.Color(19, 38, 35));

        asignacionNuevaIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignacionNuevaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/noteB.png"))); // NOI18N
        asignacionNuevaIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asignacionNuevaIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asignacionNuevaIconMouseClicked(evt);
            }
        });

        asignacionNuevaLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        asignacionNuevaLabel.setForeground(new java.awt.Color(113, 166, 111));
        asignacionNuevaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignacionNuevaLabel.setText("CREAR");
        asignacionNuevaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        asignacionVerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignacionVerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dataB.png"))); // NOI18N
        asignacionVerIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        asignacionVerLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        asignacionVerLabel.setForeground(new java.awt.Color(113, 166, 111));
        asignacionVerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignacionVerLabel.setText("VER");
        asignacionVerLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        asignacionEditarIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignacionEditarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pencilB.png"))); // NOI18N

        asignacionEditarLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        asignacionEditarLabel.setForeground(new java.awt.Color(113, 166, 111));
        asignacionEditarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignacionEditarLabel.setText("EDITAR");

        javax.swing.GroupLayout inicioAsignacionLayout = new javax.swing.GroupLayout(inicioAsignacion);
        inicioAsignacion.setLayout(inicioAsignacionLayout);
        inicioAsignacionLayout.setHorizontalGroup(
            inicioAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1281, Short.MAX_VALUE)
            .addGroup(inicioAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inicioAsignacionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(inicioAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(inicioAsignacionLayout.createSequentialGroup()
                            .addComponent(asignacionNuevaIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(170, 170, 170)
                            .addComponent(asignacionVerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(160, 160, 160)
                            .addComponent(asignacionEditarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(inicioAsignacionLayout.createSequentialGroup()
                            .addComponent(asignacionNuevaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(170, 170, 170)
                            .addComponent(asignacionVerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(160, 160, 160)
                            .addComponent(asignacionEditarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        inicioAsignacionLayout.setVerticalGroup(
            inicioAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
            .addGroup(inicioAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inicioAsignacionLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(inicioAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(asignacionNuevaIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(asignacionVerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(asignacionEditarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inicioAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(asignacionNuevaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(asignacionVerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(asignacionEditarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        principalAsignacion.add(inicioAsignacion, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tituloAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tituloAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(principalAsignacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void asignacionNuevaIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignacionNuevaIconMouseClicked
        principalAsignacion.setVisible(false);
        principalAsignacion.removeAll();
        principalAsignacion.add(nueva);
        principalAsignacion.setVisible(true);
        back.setVisible(true);
    }//GEN-LAST:event_asignacionNuevaIconMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        validarInicioAsignacion();
    }//GEN-LAST:event_backMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asignacion;
    private javax.swing.JLabel asignacionEditarIcon;
    private javax.swing.JLabel asignacionEditarLabel;
    private javax.swing.JLabel asignacionNuevaIcon;
    private javax.swing.JLabel asignacionNuevaLabel;
    private javax.swing.JLabel asignacionVerIcon;
    private javax.swing.JLabel asignacionVerLabel;
    private javax.swing.JLabel back;
    private javax.swing.JPanel inicioAsignacion;
    private javax.swing.JPanel principalAsignacion;
    private javax.swing.JPanel tituloAsignacion;
    // End of variables declaration//GEN-END:variables
}
