package Frontera;

import javax.swing.JOptionPane;

public class FramePrincipal extends javax.swing.JFrame {

    private Restaurante restaurante = new Restaurante();
    private Asignacion asignacion = new Asignacion();

    public FramePrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicioGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorPanel = new javax.swing.JPanel();
        tituloPanel = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        inicio = new javax.swing.JLabel();
        servicioDeRestaurante = new javax.swing.JLabel();
        principalPanel = new javax.swing.JPanel();
        inicioPrincipal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        restauranteLabel = new javax.swing.JLabel();
        asignacionLabel = new javax.swing.JLabel();
        restauranteLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        restauranteLabel2 = new javax.swing.JLabel();
        restauranteLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        asignacionLabel1 = new javax.swing.JLabel();

        setTitle("Restaurante");
        setUndecorated(true);
        setResizable(false);

        contenedorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloPanel.setBackground(new java.awt.Color(140, 19, 29));
        tituloPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        tituloPanel.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 11, 70, 70));

        inicio.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 22)); // NOI18N
        inicio.setForeground(new java.awt.Color(19, 38, 35));
        inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicio.setText("INICIO");
        inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioMouseClicked(evt);
            }
        });
        tituloPanel.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 21, 70, 50));

        servicioDeRestaurante.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 36)); // NOI18N
        servicioDeRestaurante.setForeground(new java.awt.Color(19, 38, 35));
        servicioDeRestaurante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        servicioDeRestaurante.setText("SERVICIO DE RESTAURANTE");
        tituloPanel.add(servicioDeRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 11, 1100, 70));

        contenedorPanel.add(tituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 90));

        principalPanel.setBackground(new java.awt.Color(113, 166, 111));
        principalPanel.setLayout(new java.awt.BorderLayout());

        inicioPrincipal.setBackground(new java.awt.Color(19, 38, 35));
        inicioPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cardB.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        inicioPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 150, 130));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/restaurantB.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        inicioPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 150, 130));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicioPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 150, 130));

        restauranteLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        restauranteLabel.setForeground(new java.awt.Color(255, 255, 255));
        restauranteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicioPrincipal.add(restauranteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 150, 30));

        asignacionLabel.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        asignacionLabel.setForeground(new java.awt.Color(113, 166, 111));
        asignacionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        asignacionLabel.setText("ASIGNACIÓN");
        asignacionLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asignacionLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asignacionLabelMouseClicked(evt);
            }
        });
        inicioPrincipal.add(asignacionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 150, 30));

        restauranteLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        restauranteLabel1.setForeground(new java.awt.Color(113, 166, 111));
        restauranteLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        restauranteLabel1.setText("RESTAURANTE");
        restauranteLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restauranteLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restauranteLabel1MouseClicked(evt);
            }
        });
        inicioPrincipal.add(restauranteLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 150, 30));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicioPrincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 150, 130));

        restauranteLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        restauranteLabel2.setForeground(new java.awt.Color(255, 255, 255));
        restauranteLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicioPrincipal.add(restauranteLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, 150, 30));

        restauranteLabel3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        restauranteLabel3.setForeground(new java.awt.Color(255, 255, 255));
        restauranteLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicioPrincipal.add(restauranteLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 150, 30));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicioPrincipal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 150, 130));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicioPrincipal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 150, 130));

        asignacionLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        asignacionLabel1.setForeground(new java.awt.Color(255, 255, 255));
        asignacionLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicioPrincipal.add(asignacionLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 150, 30));

        principalPanel.add(inicioPrincipal, java.awt.BorderLayout.CENTER);

        contenedorPanel.add(principalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1280, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseClicked
        validarInicioGUI();
    }//GEN-LAST:event_inicioMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        principalPanel.setVisible(false);
        principalPanel.removeAll();
        principalPanel.add(asignacion);
        principalPanel.setVisible(true);
        inicio.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void asignacionLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asignacionLabelMouseClicked
        principalPanel.setVisible(false);
        principalPanel.removeAll();
        principalPanel.add(asignacion);
        principalPanel.setVisible(true);
        inicio.setVisible(true);
    }//GEN-LAST:event_asignacionLabelMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        principalPanel.setVisible(false);
        principalPanel.removeAll();
        principalPanel.add(restaurante);
        principalPanel.setVisible(true);
        inicio.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void restauranteLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restauranteLabel1MouseClicked
        principalPanel.setVisible(false);
        principalPanel.removeAll();
        principalPanel.add(restaurante);
        principalPanel.setVisible(true);
        inicio.setVisible(true);
    }//GEN-LAST:event_restauranteLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    public void inicioGUI() {
        principalPanel.setVisible(false);
        principalPanel.removeAll();
        principalPanel.add(inicioPrincipal);
        principalPanel.setVisible(true);
        inicio.setVisible(false);
        asignacion.inicioAsignacion();
    }

    public void validarInicioGUI() {
        int selCon = JOptionPane.showConfirmDialog(null, "¿Desea volver al inicio?", "Confirmación", JOptionPane.OK_CANCEL_OPTION);
        if (selCon == 0) {
            principalPanel.setVisible(false);
            principalPanel.removeAll();
            principalPanel.add(inicioPrincipal);
            principalPanel.setVisible(true);
            inicio.setVisible(false);
            asignacion.inicioAsignacion();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asignacionLabel;
    private javax.swing.JLabel asignacionLabel1;
    private javax.swing.JLabel close;
    private javax.swing.JPanel contenedorPanel;
    private javax.swing.JLabel inicio;
    private javax.swing.JPanel inicioPrincipal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JLabel restauranteLabel;
    private javax.swing.JLabel restauranteLabel1;
    private javax.swing.JLabel restauranteLabel2;
    private javax.swing.JLabel restauranteLabel3;
    private javax.swing.JLabel servicioDeRestaurante;
    private javax.swing.JPanel tituloPanel;
    // End of variables declaration//GEN-END:variables
}
